services:
  nginx-rp:
    image: nginx:stable-alpine
    container_name: nginx-rp
    hostname: nginx-rp
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d/
      - ./html/index.html:/var/www/html/index.html
      #- /etc/letsencrypt:/etc/letsencrypt
networks:
  default:
    name: nginx_tier
