services:
  nginx_rp:
    image: nginx:stable-alpine
    container_name: nginx_rp_container
    hostname: nginx_rp_host
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-rp-net
    volumes:
      - './conf/nginx.conf:/etc/nginx/nginx.conf'
      - './html/index.html:/var/www/html/index.html'
      - '/etc/letsencrypt:/etc/letsencrypt'

networks:
  default:
    name: nginx-rp-net
    driver: bridge
